In [4]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("array:", arr)

# Reshaping the array
matrix = arr.reshape((5, 1))
print("Reshaped Matrix:\n", matrix)

# Performing mathematical operations
arr_squared = arr ** 2
print("Squared Array:", arr_squared)

# Generating a random matrix 
random_matrix = np.random.rand(3, 3)
print("Random Matrix:\n", random_matrix)


array: [1 2 3 4 5]
Reshaped Matrix:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Squared Array: [ 1  4  9 16 25]
Random Matrix:
 [[0.4640701  0.99070077 0.24609791]
 [0.70852005 0.09152738 0.83583313]
 [0.23590729 0.23212711 0.38317773]]


In [6]:
import pandas as pd

#Creating a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'Salary': [50000, 60000, 70000]}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

# Reading data from CSV file
# df = pd.read_csv('data.csv')

# Display the first 5 rows
print(df.head())

# Descpritive statistics of numerical columns
print(df.describe())

# Handling missing values
df.fillna(0, inplace=True)

# Filtering data 
filtered_df = df[df["Age"]>28]
print("Filtered DataFrame:\n", filtered_df)

DataFrame:
       Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
        Age   Salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0


In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score


#Sample data    
X = [[1], [2], [3], [4], [5],[1], [2], [3], [4], [5],[1], [2], [3], [4], [5]]
y = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5] #Labels

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, np.round(y_pred))
print("Model Accuracy:", accuracy)


Model Accuracy: 1.0
